In [11]:
import nltk
import pandas as pd
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
import re

In [12]:
paragraph="""Darjeeling is a city and a municipality in the Indian state of West Bengal. It is located in the Lesser Himalayas at an elevation of 2,000 metres (6,560 ft).
           It is noted for its tea industry, its views of the world's third-highest mountain Kangchenjunga, and the Darjeeling Himalayan Railway, a UNESCO World Heritage Site. 
           Darjeeling is the headquarters of the Darjeeling district which has a partially autonomous status called Gorkhaland Territorial Administration within the state of 
           West Bengal. It is also a popular tourist destination in India.
           The recorded history of the town starts from the early 19th century when the colonial administration under the British Raj set up a sanatorium and a military depot 
           in the region. Subsequently, extensive tea plantations were established in the region and tea growers developed hybrids of black tea and created new fermentation 
           techniques. The resultant distinctive Darjeeling tea is internationally recognised and ranks among the most popular black teas in the world.[6] The Darjeeling 
           Himalayan Railway connects the town with the plains and has some of the few steam locomotives still in service in India.
           Darjeeling has several British-style private schools, which attract pupils from all over India and a few neighbouring countries. The varied culture of the town 
           reflects its diverse demographic milieu comprising Lepcha, Khampa, Gorkha, Kirati, Newar, Sherpa, Bhutia, Bengali[7] and other mainland Indian ethno-linguistic groups. 
           Darjeeling, alongside its neighbouring town of Kalimpong, was the centre of the Gorkhaland social movement in the 1980s and summer 2017."""

In [13]:
sentences=nltk.sent_tokenize(paragraph)
sentences

['Darjeeling is a city and a municipality in the Indian state of West Bengal.',
 'It is located in the Lesser Himalayas at an elevation of 2,000 metres (6,560 ft).',
 "It is noted for its tea industry, its views of the world's third-highest mountain Kangchenjunga, and the Darjeeling Himalayan Railway, a UNESCO World Heritage Site.",
 'Darjeeling is the headquarters of the Darjeeling district which has a partially autonomous status called Gorkhaland Territorial Administration within the state of \n           West Bengal.',
 'It is also a popular tourist destination in India.',
 'The recorded history of the town starts from the early 19th century when the colonial administration under the British Raj set up a sanatorium and a military depot \n           in the region.',
 'Subsequently, extensive tea plantations were established in the region and tea growers developed hybrids of black tea and created new fermentation \n           techniques.',
 'The resultant distinctive Darjeeling tea is internationally recognised and ranks among the most popular black teas in the world.',
 '[6] The Darjeeling \n           Himalayan Railway connects the town with the plains and has some of the few steam locomotives still in service in India.',
 'Darjeeling has several British-style private schools, which attract pupils from all over India and a few neighbouring countries.',
 'The varied culture of the town \n           reflects its diverse demographic milieu comprising Lepcha, Khampa, Gorkha, Kirati, Newar, Sherpa, Bhutia, Bengali[7] and other mainland Indian ethno-linguistic groups.',
 'Darjeeling, alongside its neighbouring town of Kalimpong, was the centre of the Gorkhaland social movement in the 1980s and summer 2017.']

In [14]:
lemmatizing=WordNetLemmatizer()

In [15]:
corpus=[]
for i in range(len(sentences)):
    review=re.sub('[^a-zA-Z]',' ',sentences[i])
    review=review.lower()
    review=review.split()
    review=[lemmatizing.lemmatize(word) for word in review if word not in set(stopwords.words('english'))]
    review=' '.join(review)
    corpus.append(review)
corpus

['darjeeling city municipality indian state west bengal',
 'located lesser himalaya elevation metre ft',
 'noted tea industry view world third highest mountain kangchenjunga darjeeling himalayan railway unesco world heritage site',
 'darjeeling headquarters darjeeling district partially autonomous status called gorkhaland territorial administration within state west bengal',
 'also popular tourist destination india',
 'recorded history town start early th century colonial administration british raj set sanatorium military depot region',
 'subsequently extensive tea plantation established region tea grower developed hybrid black tea created new fermentation technique',
 'resultant distinctive darjeeling tea internationally recognised rank among popular black tea world',
 'darjeeling himalayan railway connects town plain steam locomotive still service india',
 'darjeeling several british style private school attract pupil india neighbouring country',
 'varied culture town reflects diverse demographic milieu comprising lepcha khampa gorkha kirati newar sherpa bhutia bengali mainland indian ethno linguistic group',
 'darjeeling alongside neighbouring town kalimpong centre gorkhaland social movement summer']

BAG OF WORDS

In [16]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer()
X=cv.fit_transform(corpus).toarray()
X

array([[0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 2],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0]], dtype=int64)

In [17]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,110,111,112,113
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,1,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,1,0,1,0,0,2
3,1,0,0,0,0,1,1,0,0,0,...,0,0,0,0,0,0,0,1,1,0
4,0,0,1,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
5,1,0,0,0,0,0,0,0,0,0,...,1,0,0,1,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,0,0,0,1,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
9,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,0,0,0,0,0,1,1,0,...,0,0,0,1,0,1,0,0,0,0
11,0,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0

TF-IDF

In [18]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
Y=tfidf.fit_transform(corpus).toarray()
Y

array([[0.        , 0.        , 0.        , ..., 0.37597081, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.43957247],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.3490798 , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [19]:
pd.DataFrame(Y)

,0,1,2,3,4,5,6,7,8,9,...,104,105,106,107,108,109,110,111,112,113
0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.375971,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.375971,0.000000,0.000000
1,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
2,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.00000,0.255919,0.000000,0.000000,0.255919,0.00000,0.255919,0.000000,0.000000,0.439572
3,0.240439,0.00000,0.000000,0.000000,0.000000,0.279967,0.240439,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.240439,0.279967,0.000000
4,0.000000,0.00000,0.481511,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.481511,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
5,0.224176,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.26103,0.000000,0.000000,0.177745,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
6,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.204393,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
7,0.000000,0.00000,0.000000,0.304539,0.000000,0.000000,0.000000,0.00000,0.00000,0.261542,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.261542
8,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.229780,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
9,0.000000,0.00000,0.000000,0.000000,0.327592,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000
10,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.22249,0.22249,0.000000,...,0.00000,0.000000,0.000000,0.151501,0.000000,0.22249,0.000000,0.000000,0.000000,0.000000
11,0.000000,0.34908,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.00000,0.000000,...,0.00000,0.000000,0.000000,0.237701,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000